version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '3010:80'
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - APPID=3333
    volumes:
      - ./src:/usr/app/src
  service2:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - APPID=4444
    volumes:
      - ./src:/usr/app/src

