version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '4010:80'
  auth1:
    build: ./authentification
    environment: 
      - APPID=1111
  auth2:
    build: ./authentification
    environment: 
      - APPID=2222
  nginx_load_balancer2:
    image: nginx
    volumes:
      - './nginx/default2.conf:/etc/nginx/nginx.conf'
    ports:
      - '3010:80'
  service1:
    build: ./services
    environment: 
      - APPID=3333
  service2:
    build: ./services
    environment: 
      - APPID=4444
    


