version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '4010:80'
  auth1:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - APPID=1111
    volumes: 
      - ./src:/usr/app/src
  auth2:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - APPID=2222
    volumes: 
      - ./src:/usr/app/src


